# Generated by Django 4.0.1 on 2022-04-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=200)),
                ('phone_number', models.IntegerField(max_length=10)),
                ('customer_complaint_message', models.TextField(blank=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('expire_date', models.DateField()),
            ],
        ),
    ]
