# Generated by Django 4.0.1 on 2022-04-13 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_inquiry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinquiry',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
