# Generated by Django 4.0.1 on 2022-04-13 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer_inquiry', '0002_alter_customerinquiry_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerinquiry',
            name='otp',
            field=models.CharField(default=django.utils.timezone.now, max_length=6),
            preserve_default=False,
        ),
    ]
