# Generated by Django 4.0.1 on 2022-04-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_inquiry', '0003_customerinquiry_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerinquiry',
            name='expire_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
